### ISSUE TITLE
ios rendering under notch

### ISSUE THREAD

**Issue by adrianvintu** [AmrAbdelmagid/connection_notifier#2]
Hello, I am using the ios emulator 15/17.0 and the widgets are rendering under the notch.

Any way to fix this?

(I am using LocalConnectionNotifier)

![Simulator Screenshot - iPhone 15 - 2023-11-21 at 12 32 36](https://github.com/AmrAbdelmagid/connection_notifier/assets/33379688/6be56459-6047-4d58-935c-f7eb7d3494dd)

**Comment by AmrAbdelmagid** [comment]
Thanks @adrianvintu for opening an issue, I will check.

**Comment by adrianvintu** [comment]
@AmrAbdelmagid  Thank you for your awesome work!

**Comment by AmrAbdelmagid** [comment]
![Screenshot 2023-12-01 at 12 58 51 AM](https://github.com/AmrAbdelmagid/connection_notifier/assets/52869694/8a63738e-b01b-4897-bd31-a4adea0dd715)

@adrianvintu This is how it looks when I run it on iOS 15/17.0 by default, I can only reproduce this when reducing the height of `ConnectionNotificationOptions`, which is the expected behavior in this case, waiting for your response.

**Comment by adrianvintu** [comment]
The problem was as you mentioned, when I set 

```
      connectionNotificationOptions: const ConnectionNotificationOptions(
        height: 60,
```

My bad, sorry, you can close this ticket.
